### ISSUE TITLE
GitHub .md URL for Review-1 not opening....

### ISSUE THREAD

**Issue by ghost** [gopesh-code/Ovulive#3]
Submit the GitHub .md URL for second attempt submission for Review-1.
What is submitted on Moodle is [https://moovit.vit.ac.in/pluginfile.php/902912/assignsubmission_onlinetext/submissions_onlinetext/253154/README.md](https://moovit.vit.ac.in/pluginfile.php/902912/assignsubmission_onlinetext/submissions_onlinetext/253154/README.md)

**Comment by gopesh-code** [comment]
Sorry for the delay due the CATs sir, please try to access the repository now, it has been updated on Moodle as well.
https://github.com/gopesh-code/Ovulive
